// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'truckman.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

TruckMan _$TruckManFromJson(Map<String, dynamic> json) {
  return TruckMan(
    id: json['id'] as int?,
    noOfTruckManRequest: json['noOfTruckManRequest'] as int?,
    customerCount: json['customerCount'] as int?,
    tripCount: json['tripCount'] as int?,
    paymentCount: json['paymentCount'] as int?,
    noOfTruckRequest: json['noOfTruckRequest'] as int?,
    noOfCustomerRequest: json['noOfCustomerRequest'] as int?,
    noOfPaymentRequest: json['noOfPaymentRequest'] as int?,
    firstName: json['firstName'] as String?,
    email: json['email'] as String?,
    password: json['password'] as String?,
    customerSupportNumber: json['customerSupportNumber'] as String?,
    tDS: json['tDS'] as String?,
    panCard: json['panCard'] as String?,
    aadharCard: json['aadharCard'] as String?,
    accountNumber: json['accountNumber'] as String?,
    cancelCheque: json['cancelCheque'] as String?,
    vehicleRC: json['vehicleRC'] as String?,
    vehicleNumber: json['vehicleNumber'] as String?,
    isApprove: json['isApprove'] as bool?,
    isEnable: json['isEnable'] as bool?,
    monthYears: json['monthYears'] as String?,
    mobileNumber: json['mobileNumber'] as String,
    profileImage: json['profileImage'] as String?,
    lastLogin: json['lastLogin'] as String?,
    generalAccountStatusId: json['generalAccountStatusId'] as int?,
    generalAccountStatusName: json['generalAccountStatusName'] as String?,
    deviceToken: json['deviceToken'] as String,
    deviceType: json['deviceType'] as String,
    uDID: json['uDID'] as String,
    iMEI: json['iMEI'] as String,
    oTP: json['oTP'] as int?,
    isSignup: json['isSignup'] as bool?,
    tDSStr: json['tDSStr'] as String?,
    panCardStr: json['panCardStr'] as String?,
    aadharCardStr: json['aadharCardStr'] as String?,
    cancelChequeStr: json['cancelChequeStr'] as String?,
    lastLoginStr: json['lastLoginStr'] as String?,
    isActive: json['isActive'] as bool?,
    createdDate: json['createdDate'] as String?,
    createdBy: json['createdBy'] as int?,
    updatedDate: json['updatedDate'] as String?,
    updatedBy: json['updatedBy'] as int?,
    deletedDate: json['deletedDate'] as String?,
    deletedBy: json['deletedBy'] as int?,
    createdDateStr: json['createdDateStr'] as String?,
    updatedDateStr: json['updatedDateStr'] as String?,
    deletedDateStr: json['deletedDateStr'] as String?,
  );
}

Map<String, dynamic> _$TruckManToJson(TruckMan instance) => <String, dynamic>{
      'id': instance.id,
      'noOfTruckManRequest': instance.noOfTruckManRequest,
      'customerCount': instance.customerCount,
      'tripCount': instance.tripCount,
      'paymentCount': instance.paymentCount,
      'noOfTruckRequest': instance.noOfTruckRequest,
      'noOfCustomerRequest': instance.noOfCustomerRequest,
      'noOfPaymentRequest': instance.noOfPaymentRequest,
      'firstName': instance.firstName,
      'email': instance.email,
      'password': instance.password,
      'customerSupportNumber': instance.customerSupportNumber,
      'tDS': instance.tDS,
      'panCard': instance.panCard,
      'aadharCard': instance.aadharCard,
      'accountNumber': instance.accountNumber,
      'cancelCheque': instance.cancelCheque,
      'vehicleRC': instance.vehicleRC,
      'vehicleNumber': instance.vehicleNumber,
      'isApprove': instance.isApprove,
      'isEnable': instance.isEnable,
      'monthYears': instance.monthYears,
      'mobileNumber': instance.mobileNumber,
      'profileImage': instance.profileImage,
      'lastLogin': instance.lastLogin,
      'generalAccountStatusId': instance.generalAccountStatusId,
      'generalAccountStatusName': instance.generalAccountStatusName,
      'deviceToken': instance.deviceToken,
      'deviceType': instance.deviceType,
      'uDID': instance.uDID,
      'iMEI': instance.iMEI,
      'oTP': instance.oTP,
      'isSignup': instance.isSignup,
      'tDSStr': instance.tDSStr,
      'panCardStr': instance.panCardStr,
      'aadharCardStr': instance.aadharCardStr,
      'cancelChequeStr': instance.cancelChequeStr,
      'lastLoginStr': instance.lastLoginStr,
      'isActive': instance.isActive,
      'createdDate': instance.createdDate,
      'createdBy': instance.createdBy,
      'updatedDate': instance.updatedDate,
      'updatedBy': instance.updatedBy,
      'deletedDate': instance.deletedDate,
      'deletedBy': instance.deletedBy,
      'createdDateStr': instance.createdDateStr,
      'updatedDateStr': instance.updatedDateStr,
      'deletedDateStr': instance.deletedDateStr,
    };
